// Nordwind Bank alert triage - C4 model (source of truth).
// Exported to docs/c4/generated by `task c4` and .github/workflows/c4.yml;
// ci.yml fails a PR whose generated diagrams are stale.
workspace "Nordwind Bank - alert triage" "One triage brain on AWS fed by three bank estates (AWS serverless, Azure serverless, Kubernetes on kind)." {

    !identifiers hierarchical

    model {
        oncall = person "On-call engineer" "Reads verdicts on the incident console and teaches known issues."
        operator = person "Chaos operator" "Fires synthetic alerts and injects faults with the bankops CLI."

        claude = softwareSystem "Anthropic API" "Claude Haiku 4.5, reached through ADK's LiteLLM adapter." "External"

        cli = softwareSystem "bankops CLI" "fire, chaos, teach, tail, estate up|down" "Tool"

        triage = softwareSystem "Alert Triage" "Ingests alerts from every estate, triages them with Claude, remembers known issues, publishes verdicts." {
            ingest = container "ingest" "HMAC-verifies webhooks, normalises to the canonical alert, scrubs PII, dedups by fingerprint, enqueues." "AWS Lambda (Python)"
            queue = container "alerts queue" "Decouples ingestion from LLM latency; dead-letter queue for poison alerts." "SQS + DLQ" "Queue"
            worker = container "triage worker" "Runs the three-role ADK workflow once per alert and writes the verdict." "AWS Lambda container image (Python, Google ADK)" {
                agent = component "triage agent" "Root agent: pulls alert context, checks the known-issues store, decides the hand-off." "ADK Agent"
                researcher = component "researcher" "Characterises a genuinely new error from its text alone: cause category, severity, next step. Deliberately tool-less." "ADK Agent"
                reporter = component "reporter" "Produces the final text in exactly one of two formats plus a machine-readable verdict block." "ADK Agent"
                tools = component "tools" "get_alert, get_recent_alerts, check_known, remember_issue" "Python functions"
                knownStore = component "KnownIssueStore" "JsonFileStore for tests and local runs, DynamoStore in the cloud." "Python interface + adapters"
                llm = component "LiteLlm model adapter" "anthropic/claude-haiku-4-5" "google.adk.models.lite_llm"
            }
            store = container "alerts, verdicts, known-issues" "Alert log, one verdict per alert, taught known issues per service." "DynamoDB (3 tables)" "Database"
            api = container "console API" "Reads alerts and verdicts; accepts taught known issues. Bearer-token protected (v1)." "AWS Lambda + API Gateway HTTP API"
            console = container "incident console" "Live alert list, verdicts, known-issues editor." "Static site on S3 + CloudFront at triage.serhiykucherenko.dev" "Browser"
            secrets = container "secrets" "Anthropic key and webhook HMAC secret." "SSM Parameter Store (SecureString)"
            dashboard = container "self-observability" "Ingest rate, verdict latency p50/p95, tokens per day, DLQ depth; SLO 95% of verdicts within 90 s." "CloudWatch dashboard + alarms"
        }

        awsEstate = softwareSystem "Nordwind serverless estate (AWS)" "Three bank services on Lambda with CloudWatch alarms." {
            payments = container "payments" "Card payment authorisation API. Chaos: errors, latency, pool." "AWS Lambda (Python)"
            ledger = container "ledger" "Double-entry posting worker fed by SQS. Chaos: reconciliation-mismatch, lag." "AWS Lambda (Python)"
            auth = container "auth" "Token issuance / JWKS. Chaos: jwks-rotation, lockouts." "AWS Lambda (Python)"
            alarms = container "alarm topic" "CloudWatch alarm state changes fan out here." "SNS" "Queue"
        }

        azureEstate = softwareSystem "Nordwind serverless estate (Azure)" "One bank service on Azure Functions, Azure Monitor alerts, and the always-on alert forwarder." {
            notifications = container "customer-notifications" "SMS / e-mail fan-out. Chaos: provider-429, backlog." "Azure Function (Python)"
            monitor = container "Azure Monitor" "Metric alert rules + action group." "Azure Monitor"
            forwarder = container "alert forwarder" "Receives Azure Monitor action-group calls and Alertmanager route-B webhooks, signs with HMAC, posts to ingest." "Azure Function (Python)"
        }

        k8sEstate = softwareSystem "Nordwind Kubernetes estate (kind)" "Three bank services on Kubernetes with Prometheus, Alertmanager and a Strimzi Kafka backbone. Runs in kind on a laptop or a GitHub Actions runner." {
            cards = container "cards-authorization" "ISO-8583-style auth switch; produces card.authorized. Chaos: timeouts, issuer-down." "Deployment (Python)"
            fraud = container "fraud-scoring" "Consumes card.authorized, produces fraud.scored. Chaos: model-drift, latency, crashloop, lag." "Deployment (Python)"
            openBanking = container "open-banking-api" "PSD2 third-party API gateway; consumes fraud.scored. Chaos: rate-limit-storm, cert-expiry." "Deployment (Python)"
            kafka = container "Kafka" "Topics: card.authorized, fraud.scored, alerts.raw. SASL/SCRAM per client." "Strimzi (KRaft, 1 broker) + kafka-exporter" "Queue"
            prometheus = container "Prometheus + Alertmanager" "Scrapes services and kafka-exporter; alert rules; Alertmanager routes A (Kafka) and B (HTTPS)." "kube-prometheus-stack"
            bridge = container "alerts-bridge" "Alertmanager webhook receiver that produces canonical alerts to alerts.raw." "Deployment (Python)"
            relay = container "kafka-relay" "Consumes alerts.raw, signs with HMAC, POSTs to ingest - the hop out of Kafka." "Deployment (Python)"
        }

        // people
        operator -> cli "runs"
        oncall -> triage.console "reads verdicts, teaches known issues" "HTTPS"

        // bankops
        cli -> triage.ingest "fire: synthetic alert" "HTTPS + HMAC"
        cli -> awsEstate.payments "chaos: set fault flag" "Lambda invoke"
        cli -> azureEstate.notifications "chaos: set fault flag" "HTTPS"
        cli -> k8sEstate.cards "chaos: patch ConfigMap" "kubectl"

        // AWS estate
        awsEstate.payments -> awsEstate.alarms "alarm state change"
        awsEstate.ledger -> awsEstate.alarms "alarm state change"
        awsEstate.auth -> awsEstate.alarms "alarm state change"
        awsEstate.alarms -> triage.ingest "notification" "SNS subscription"

        // Azure estate
        azureEstate.notifications -> azureEstate.monitor "telemetry"
        azureEstate.monitor -> azureEstate.forwarder "action group webhook" "HTTPS"
        azureEstate.forwarder -> triage.ingest "canonical alert" "HTTPS + HMAC"

        // Kubernetes estate
        k8sEstate.cards -> k8sEstate.kafka "produce card.authorized"
        k8sEstate.fraud -> k8sEstate.kafka "consume card.authorized, produce fraud.scored"
        k8sEstate.openBanking -> k8sEstate.kafka "consume fraud.scored"
        k8sEstate.prometheus -> k8sEstate.cards "scrapes /metrics"
        k8sEstate.prometheus -> k8sEstate.fraud "scrapes /metrics"
        k8sEstate.prometheus -> k8sEstate.openBanking "scrapes /metrics"
        k8sEstate.prometheus -> k8sEstate.kafka "scrapes kafka-exporter (consumer lag)"
        k8sEstate.prometheus -> k8sEstate.bridge "route A: Alertmanager webhook"
        k8sEstate.bridge -> k8sEstate.kafka "produce alerts.raw"
        k8sEstate.kafka -> k8sEstate.relay "consume alerts.raw"
        k8sEstate.relay -> triage.ingest "canonical alert" "HTTPS + HMAC"
        k8sEstate.prometheus -> azureEstate.forwarder "route B: KafkaBrokerDown, KafkaRelayLag, or route A failing" "HTTPS"

        // brain
        triage.ingest -> triage.store "put alert"
        triage.ingest -> triage.queue "enqueue alert id"
        triage.queue -> triage.worker "triggers"
        triage.worker -> triage.store "read alert + known issues, write verdict"
        triage.worker -> triage.secrets "read Anthropic key + HMAC secret"
        triage.worker -> triage.dashboard "latency + token metrics"
        triage.worker -> claude "triage / research / report turns" "HTTPS"
        triage.console -> triage.api "GET alerts, verdicts; POST known-issue" "HTTPS"
        triage.api -> triage.store "query / put"

        // worker internals
        triage.worker.agent -> triage.worker.tools "get_alert, get_recent_alerts, check_known, remember_issue"
        triage.worker.agent -> triage.worker.researcher "transfer: new error"
        triage.worker.agent -> triage.worker.reporter "transfer: known or characterised error"
        triage.worker.researcher -> triage.worker.reporter "characterisation, via the root agent"
        triage.worker.tools -> triage.worker.knownStore "find_known / add_known"
        triage.worker.knownStore -> triage.store "DynamoStore reads/writes"
        triage.worker.tools -> triage.store "get_alert / get_recent_alerts"
        triage.worker.agent -> triage.worker.llm "model turns"
        triage.worker.researcher -> triage.worker.llm "model turns"
        triage.worker.reporter -> triage.worker.llm "model turns"
        triage.worker.llm -> claude "HTTPS"

        demo = deploymentEnvironment "demo" {
            deploymentNode "GitHub" "" "github.com" {
                deploymentNode "Actions runner" "ubuntu-latest, 7 GB" "estate-demo.yml" {
                    deploymentNode "kind cluster" "Kubernetes in Docker" "kind" {
                        containerInstance k8sEstate.cards
                        containerInstance k8sEstate.fraud
                        containerInstance k8sEstate.openBanking
                        containerInstance k8sEstate.kafka
                        containerInstance k8sEstate.prometheus
                        containerInstance k8sEstate.bridge
                        containerInstance k8sEstate.relay
                    }
                }
            }
            deploymentNode "Laptop" "" "Docker Desktop" {
                deploymentNode "kind cluster (dev)" "" "kind" {
                    containerInstance k8sEstate.cards
                    containerInstance k8sEstate.fraud
                    containerInstance k8sEstate.openBanking
                    containerInstance k8sEstate.kafka
                    containerInstance k8sEstate.prometheus
                    containerInstance k8sEstate.bridge
                    containerInstance k8sEstate.relay
                }
            }
            deploymentNode "AWS" "eu-north-1" "Terraform: infra/aws" {
                deploymentNode "Lambda" "" "AWS Lambda" {
                    containerInstance triage.ingest
                    containerInstance triage.worker
                    containerInstance awsEstate.payments
                    containerInstance awsEstate.ledger
                    containerInstance awsEstate.auth
                }
                deploymentNode "API Gateway" "api.triage.serhiykucherenko.dev" "Amazon API Gateway (HTTP API)" {
                    containerInstance triage.api
                }
                deploymentNode "SQS" "" "Amazon SQS" {
                    containerInstance triage.queue
                }
                deploymentNode "SNS" "" "Amazon SNS" {
                    containerInstance awsEstate.alarms
                }
                deploymentNode "DynamoDB" "" "Amazon DynamoDB" {
                    containerInstance triage.store
                }
                deploymentNode "CloudFront + S3" "triage.serhiykucherenko.dev" "Amazon CloudFront" {
                    containerInstance triage.console
                }
                deploymentNode "SSM" "" "Parameter Store" {
                    containerInstance triage.secrets
                }
                deploymentNode "CloudWatch" "" "Amazon CloudWatch" {
                    containerInstance triage.dashboard
                }
            }
            deploymentNode "Azure" "westeurope" "Terraform: infra/azure" {
                deploymentNode "Function App (consumption)" "" "Azure Functions" {
                    containerInstance azureEstate.notifications
                    containerInstance azureEstate.forwarder
                }
                deploymentNode "Azure Monitor" "" "Azure Monitor" {
                    containerInstance azureEstate.monitor
                }
            }
            deploymentNode "Anthropic" "" "api.anthropic.com" {
                softwareSystemInstance claude
            }
            deploymentNode "Cloudflare" "parent zone serhiykucherenko.dev - NS delegation of triage.* to Route 53" "Cloudflare DNS" {
                infrastructureNode "NS delegation"
            }
        }
    }

    views {
        systemContext triage "context" "Level 1 - who and what talks to the triage system." {
            include *
            autolayout lr
        }

        container triage "containers" "Level 2 - the triage brain and its inbound sources." {
            include *
            autolayout lr
        }

        container k8sEstate "k8s-estate" "Level 2 - the Kubernetes estate: services, Kafka, Prometheus, the two alert routes." {
            include *
            include triage.ingest azureEstate.forwarder
            autolayout lr
        }

        component triage.worker "worker-components" "Level 3 - inside the triage worker: the three ADK roles, tools, store adapters." {
            include *
            autolayout lr
        }

        deployment * demo "deployment" "Where every container runs in the demo environment." {
            include *
            autolayout lr
        }

        styles {
            element "Person" {
                shape person
                background #0f766e
                color #ffffff
            }
            element "Software System" {
                background #1c2530
                color #ffffff
            }
            element "External" {
                background #8fa1b0
                color #ffffff
            }
            element "Tool" {
                background #5b6b7a
                color #ffffff
            }
            element "Container" {
                background #14b8a6
                color #0e1419
            }
            element "Component" {
                background #99f6e4
                color #0e1419
            }
            element "Database" {
                shape cylinder
            }
            element "Queue" {
                shape pipe
            }
            element "Browser" {
                shape webbrowser
            }
        }
    }
}
