// Nordwind Bank alert triage - C4 model (source of truth).
// Exported to docs/c4/generated by `task c4` and .github/workflows/c4.yml;
// ci.yml fails a PR whose generated diagrams are stale.
workspace "Nordwind Bank - alert triage" "One triage brain on AWS fed by three bank estates (AWS serverless, Azure serverless, Kubernetes on kind)." {

    !identifiers hierarchical

    model {
        oncall = person "On-call engineer" "Reads verdicts on the incident console and teaches known issues."
        operator = person "Chaos operator" "Fires synthetic alerts and injects faults with the bankops CLI."

        claude = softwareSystem "Anthropic API" "Claude Haiku 4.5, reached through ADK's LiteLLM adapter." "External"

        cli = softwareSystem "bankops CLI" "fire, chaos, teach, tail, estate up|down" "Tool"

        triage = softwareSystem "Alert Triage" "Ingests alerts from every estate, triages them with Claude, remembers known issues, publishes verdicts." {
            ingest = container "ingest" "HMAC-verifies webhooks, normalises to the canonical alert, scrubs PII, dedups by fingerprint, enqueues." "AWS Lambda (Python)"
            queue = container "alerts queue" "Decouples ingestion from LLM latency; dead-letter queue for poison alerts." "SQS + DLQ" "Queue"
            worker = container "triage worker" "Runs the three-role ADK workflow once per alert and writes the verdict." "AWS Lambda container image (Python, Google ADK)" {
                agent = component "triage agent" "Root agent: pulls alert context, checks the known-issues store, decides the hand-off." "ADK Agent"
                researcher = component "researcher" "Characterises a genuinely new error from its text alone: cause category, severity, next step. Deliberately tool-less." "ADK Agent"
                reporter = component "reporter" "Produces the final text in exactly one of two formats plus a machine-readable verdict block." "ADK Agent"
                tools = component "tools" "get_alert, get_recent_alerts, check_known, remember_issue" "Python functions"
                knownStore = component "KnownIssueStore" "JsonFileStore for tests and local runs, DynamoStore in the cloud." "Python interface + adapters"
                llm = component "LiteLlm model adapter" "anthropic/claude-haiku-4-5" "google.adk.models.lite_llm"
            }
            store = container "alerts, verdicts, known-issues" "Alert log, one verdict per alert, taught known issues per service." "DynamoDB (3 tables)" "Database"
            api = container "console API" "Reads alerts and verdicts; accepts taught known issues. Bearer-token protected (v1)." "AWS Lambda + API Gateway HTTP API"
            console = container "incident console" "Live alert list, verdicts, known-issues editor." "Static site on S3 + CloudFront at triage.serhiykucherenko.dev" "Browser"
            secrets = container "secrets" "Anthropic key and webhook HMAC secret." "SSM Parameter Store (SecureString)"
            dashboard = container "self-observability" "Ingest rate, verdict latency p50/p95, tokens per day, DLQ depth; SLO 95% of verdicts within 90 s." "CloudWatch dashboard + alarms"
        }

        awsEstate = softwareSystem "Nordwind serverless estate (AWS)" "Three bank services on Lambda with CloudWatch alarms." {
            payments = container "payments" "Card payment authorisation API. Chaos: errors, latency, pool." "AWS Lambda (Python)"
            ledgerQueue = container "ledger queue" "Decouples payments from ledger posting; DLQ after 5 failed attempts." "SQS + DLQ" "Queue"
            ledger = container "ledger" "Double-entry posting worker fed by SQS. Chaos: reconciliation-mismatch, lag." "AWS Lambda (Python)"
            auth = container "auth" "Token issuance / JWKS. Chaos: jwks-rotation, lockouts." "AWS Lambda (Python)"
            alarms = container "alarm topic" "CloudWatch alarm state changes fan out here." "SNS" "Queue"
            faults = container "faults" "One fault flag per service, set by bankops chaos or the console API." "DynamoDB" "Database"
        }

        azureEstate = softwareSystem "Nordwind serverless estate (Azure)" "One bank service on Azure Functions, Azure Monitor alerts, and the always-on alert forwarder." {
            notifications = container "customer-notifications" "SMS / e-mail fan-out. Chaos: provider-429, backlog." "Azure Function (Python)"
            appInsights = container "Application Insights" "Custom metrics (provider_429, notifications_backlog) and exceptions from customer-notifications; the alert rules query it." "Application Insights + Log Analytics"
            monitor = container "Azure Monitor" "Metric alert rules + action group." "Azure Monitor"
            forwarder = container "alert forwarder" "Receives Azure Monitor action-group calls and Alertmanager route-B webhooks, signs with HMAC, posts to ingest." "Azure Function (Python)"
        }

        k8sEstate = softwareSystem "Nordwind Kubernetes estate (kind)" "Three bank services plus a Kafka backbone on Kubernetes, with Prometheus and Alertmanager routing alerts over Kafka (route A) or straight to the forwarder (route B, Kafka's own alerts). Runs in kind on a laptop or a GitHub Actions runner." {
            cards = container "cards-authorization" "ISO-8583-style auth switch. Chaos: timeouts, issuer-down." "Deployment (Python)"
            fraud = container "fraud-scoring" "ML scoring. Chaos: model-drift, latency, crashloop, lag." "Deployment (Python)"
            openBanking = container "open-banking-api" "PSD2 third-party API gateway. Chaos: rate-limit-storm, cert-expiry." "Deployment (Python)"
            kafka = container "kafka" "Business event backbone and alert transport: card.authorized, fraud.scored, alerts.raw." "Strimzi (KRaft)" "Queue"
            kafkaExporter = container "kafka-exporter" "Exports per-consumer-group lag (kafka_consumergroup_lag). Chaos: broker-down (scales the broker KafkaNodePool to 0)." "Strimzi kafka-exporter"
            alertsBridge = container "alerts-bridge" "Alertmanager webhook receiver; produces one Kafka message per alert to alerts.raw (route A's first hop)." "Deployment (Python)"
            kafkaRelay = container "kafka-relay" "Consumes alerts.raw, HMAC-signs, and POSTs to ingest (route A's second hop)." "Deployment (Python)"
            prometheus = container "prometheus" "Scrapes services, Kafka, and kafka-exporter; evaluates the eleven PrometheusRules." "kube-prometheus-stack"
            alertmanager = container "alertmanager" "Routes firing alerts to route-a-kafka by default; Kafka's own alerts (KafkaBrokerDown, KafkaRelayLag, AlertsBridgeDown, KafkaRelayDown) take route-b-forwarder instead." "kube-prometheus-stack"
        }

        // people
        operator -> cli "runs"
        oncall -> triage.console "reads verdicts, teaches known issues" "HTTPS"

        // bankops
        cli -> triage.ingest "fire: synthetic alert" "HTTPS + HMAC"
        cli -> awsEstate.payments "chaos: set fault flag" "Lambda invoke"
        cli -> azureEstate.notifications "chaos: set fault flag" "HTTPS"
        cli -> k8sEstate.cards "chaos: patch ConfigMap" "kubectl"

        // AWS estate
        awsEstate.payments -> awsEstate.ledgerQueue "enqueue authorisation"
        awsEstate.ledgerQueue -> awsEstate.ledger "triggers"
        awsEstate.payments -> awsEstate.alarms "alarm state change"
        awsEstate.ledger -> awsEstate.alarms "alarm state change"
        awsEstate.auth -> awsEstate.alarms "alarm state change"
        awsEstate.alarms -> triage.ingest "notification" "SNS subscription"
        awsEstate.payments -> awsEstate.faults "read fault flag"
        awsEstate.ledger -> awsEstate.faults "read fault flag"
        awsEstate.auth -> awsEstate.faults "read fault flag"
        triage.api -> awsEstate.faults "GET/POST/DELETE chaos"

        // Azure estate
        azureEstate.notifications -> triage.api "GET /chaos (bearer)" "HTTPS"
        azureEstate.notifications -> azureEstate.appInsights "custom metrics"
        azureEstate.monitor -> azureEstate.forwarder "action group webhook (common alert schema)" "HTTPS"
        azureEstate.forwarder -> triage.ingest "canonical alert" "HTTPS + HMAC"

        // Kubernetes estate
        k8sEstate.prometheus -> k8sEstate.cards "scrape"
        k8sEstate.prometheus -> k8sEstate.fraud "scrape"
        k8sEstate.prometheus -> k8sEstate.openBanking "scrape"
        k8sEstate.prometheus -> k8sEstate.kafka "scrape broker JMX"
        k8sEstate.prometheus -> k8sEstate.kafkaExporter "scrape"
        k8sEstate.prometheus -> k8sEstate.alertsBridge "scrape"
        k8sEstate.prometheus -> k8sEstate.kafkaRelay "scrape"
        k8sEstate.prometheus -> k8sEstate.alertmanager "firing alerts"
        k8sEstate.cards -> k8sEstate.kafka "produce card.authorized"
        k8sEstate.fraud -> k8sEstate.kafka "consume card.authorized, produce fraud.scored"
        k8sEstate.openBanking -> k8sEstate.kafka "consume fraud.scored"
        k8sEstate.kafkaExporter -> k8sEstate.kafka "read consumer group offsets"
        k8sEstate.alertmanager -> k8sEstate.alertsBridge "route A webhook" "HTTPS"
        k8sEstate.alertsBridge -> k8sEstate.kafka "produce alerts.raw"
        k8sEstate.kafkaRelay -> k8sEstate.kafka "consume alerts.raw"
        k8sEstate.kafkaRelay -> triage.ingest "HTTPS + HMAC (route A)"
        k8sEstate.alertmanager -> azureEstate.forwarder "route B (Kafka's own alerts)" "HTTPS"

        // brain
        triage.ingest -> triage.store "put alert"
        triage.ingest -> triage.queue "enqueue alert id"
        triage.queue -> triage.worker "triggers"
        triage.worker -> triage.store "read alert + known issues, write verdict"
        triage.worker -> triage.secrets "read Anthropic key + HMAC secret"
        triage.worker -> triage.dashboard "latency + token metrics"
        triage.worker -> claude "triage / research / report turns" "HTTPS"
        triage.console -> triage.api "GET alerts, verdicts; POST known-issue" "HTTPS"
        triage.api -> triage.store "query / put"

        // worker internals
        triage.worker.agent -> triage.worker.tools "get_alert, get_recent_alerts, check_known, remember_issue"
        triage.worker.agent -> triage.worker.researcher "transfer: new error"
        triage.worker.agent -> triage.worker.reporter "transfer: known or characterised error"
        triage.worker.researcher -> triage.worker.reporter "characterisation, via the root agent"
        triage.worker.tools -> triage.worker.knownStore "find_known / add_known"
        triage.worker.knownStore -> triage.store "DynamoStore reads/writes"
        triage.worker.tools -> triage.store "get_alert / get_recent_alerts"
        triage.worker.agent -> triage.worker.llm "model turns"
        triage.worker.researcher -> triage.worker.llm "model turns"
        triage.worker.reporter -> triage.worker.llm "model turns"
        triage.worker.llm -> claude "HTTPS"

        demo = deploymentEnvironment "demo" {
            deploymentNode "AWS" "eu-north-1" "Terraform: infra/aws" {
                deploymentNode "Lambda" "" "AWS Lambda" {
                    containerInstance triage.ingest
                    containerInstance triage.worker
                    containerInstance awsEstate.payments
                    containerInstance awsEstate.ledger
                    containerInstance awsEstate.auth
                }
                deploymentNode "API Gateway" "api.triage.serhiykucherenko.dev" "Amazon API Gateway (HTTP API)" {
                    containerInstance triage.api
                }
                deploymentNode "SQS" "" "Amazon SQS" {
                    containerInstance triage.queue
                    containerInstance awsEstate.ledgerQueue
                }
                deploymentNode "SNS" "" "Amazon SNS" {
                    containerInstance awsEstate.alarms
                }
                deploymentNode "DynamoDB" "" "Amazon DynamoDB" {
                    containerInstance triage.store
                    containerInstance awsEstate.faults
                }
                deploymentNode "CloudFront + S3" "triage.serhiykucherenko.dev" "Amazon CloudFront" {
                    containerInstance triage.console
                }
                deploymentNode "SSM" "" "Parameter Store" {
                    containerInstance triage.secrets
                }
                deploymentNode "CloudWatch" "" "Amazon CloudWatch" {
                    containerInstance triage.dashboard
                }
                deploymentNode "ECR" "" "Amazon ECR (Terraform: infra/aws-ecr)" {
                    infrastructureNode "triage-worker image" "Immutable image tagged by git SHA (also `:latest`); built and pushed by deploy.yml's `image` job, run by the Lambda above."
                }
            }
            deploymentNode "Azure" "swedencentral" "Terraform: infra/azure" {
                deploymentNode "Function App (consumption)" "" "Azure Functions" {
                    containerInstance azureEstate.notifications
                    containerInstance azureEstate.forwarder
                }
                deploymentNode "Application Insights + Log Analytics" "" "Azure Monitor" {
                    containerInstance azureEstate.appInsights
                }
                deploymentNode "Azure Monitor" "" "Azure Monitor" {
                    containerInstance azureEstate.monitor
                }
            }
            deploymentNode "Anthropic" "" "api.anthropic.com" {
                softwareSystemInstance claude
            }
            deploymentNode "Cloudflare" "parent zone serhiykucherenko.dev - NS delegation of triage.* to Route 53" "Cloudflare DNS" {
                infrastructureNode "NS delegation"
            }
        }

        kind = deploymentEnvironment "kind" {
            deploymentNode "Laptop" "" "Docker Desktop, ~6 GB RAM" {
                deploymentNode "kind cluster" "task estate-up" "kind" {
                    containerInstance k8sEstate.cards
                    containerInstance k8sEstate.fraud
                    containerInstance k8sEstate.openBanking
                    containerInstance k8sEstate.kafka
                    containerInstance k8sEstate.kafkaExporter
                    containerInstance k8sEstate.alertsBridge
                    containerInstance k8sEstate.kafkaRelay
                    containerInstance k8sEstate.prometheus
                    containerInstance k8sEstate.alertmanager
                }
            }
            deploymentNode "GitHub Actions runner" "ubuntu-latest" "estate-demo.yml" {
                deploymentNode "kind cluster" "task estate-up" "kind" {
                    containerInstance k8sEstate.cards
                    containerInstance k8sEstate.fraud
                    containerInstance k8sEstate.openBanking
                    containerInstance k8sEstate.kafka
                    containerInstance k8sEstate.kafkaExporter
                    containerInstance k8sEstate.alertsBridge
                    containerInstance k8sEstate.kafkaRelay
                    containerInstance k8sEstate.prometheus
                    containerInstance k8sEstate.alertmanager
                }
            }
        }
    }

    views {
        systemContext triage "context" "Level 1 - who and what talks to the triage system." {
            include *
            autolayout lr
        }

        container triage "containers" "Level 2 - the triage brain and its inbound sources." {
            include *
            autolayout lr
        }

        container k8sEstate "k8s-estate" "Level 2 - the Kubernetes estate: three services, Kafka, alerts-bridge, kafka-relay, Prometheus, Alertmanager routing to both routes." {
            include *
            include triage.ingest azureEstate.forwarder
            autolayout lr
        }

        component triage.worker "worker-components" "Level 3 - inside the triage worker: the three ADK roles, tools, store adapters." {
            include *
            autolayout lr
        }

        dynamic k8sEstate "route-a" "an alert travels over Kafka (route A)" {
            k8sEstate.prometheus -> k8sEstate.alertmanager "rule fires"
            k8sEstate.alertmanager -> k8sEstate.alertsBridge "route A webhook"
            k8sEstate.alertsBridge -> k8sEstate.kafka "produce alerts.raw"
            k8sEstate.kafkaRelay -> k8sEstate.kafka "consume alerts.raw"
            k8sEstate.kafkaRelay -> triage.ingest "HTTPS + HMAC"
            autolayout lr
        }

        dynamic k8sEstate "route-b" "the alert about Kafka takes route B" {
            k8sEstate.prometheus -> k8sEstate.alertmanager "KafkaBrokerDown fires"
            k8sEstate.alertmanager -> azureEstate.forwarder "route B webhook"
            azureEstate.forwarder -> triage.ingest "HTTPS + HMAC"
            autolayout lr
        }

        deployment * demo "deployment" "Where every container runs in the demo environment (AWS, Azure, Anthropic, Cloudflare)." {
            include *
            autolayout lr
        }

        deployment * kind "deployment-kind" "Where the Kubernetes estate runs: laptop for development, GitHub Actions for the repeatable estate-demo.yml." {
            include *
            autolayout lr
        }

        styles {
            element "Person" {
                shape person
                background #0f766e
                color #ffffff
            }
            element "Software System" {
                background #1c2530
                color #ffffff
            }
            element "External" {
                background #8fa1b0
                color #ffffff
            }
            element "Tool" {
                background #5b6b7a
                color #ffffff
            }
            element "Container" {
                background #14b8a6
                color #0e1419
            }
            element "Component" {
                background #99f6e4
                color #0e1419
            }
            element "Database" {
                shape cylinder
            }
            element "Queue" {
                shape pipe
            }
            element "Browser" {
                shape webbrowser
            }
        }
    }
}
